enum AchievementType {
  // TODO: generic COMPLETED_LEVELS achievement with an array of values in achievementInfo
  COMPLETED_LEVELS_100 = 'COMPLETED_LEVELS_100',
  COMPLETED_LEVELS_500 = 'COMPLETED_LEVELS_500',
  COMPLETED_LEVELS_1000 = 'COMPLETED_LEVELS_1000',
  COMPLETED_LEVELS_2000 = 'COMPLETED_LEVELS_2000',
  COMPLETED_LEVELS_3000 = 'COMPLETED_LEVELS_3000',
  COMPLETED_LEVELS_4000 = 'COMPLETED_LEVELS_4000',
  COMPLETED_LEVELS_5000 = 'COMPLETED_LEVELS_5000',
  PLAYER_RANK_KINDERGARTEN = 'PLAYER_RANK_KINDERGARTEN',
  PLAYER_RANK_ELEMENTARY = 'PLAYER_RANK_ELEMENTARY',
  PLAYER_RANK_JUNIOR_HIGH = 'PLAYER_RANK_JUNIOR_HIGH',
  PLAYER_RANK_HIGH_SCHOOL = 'PLAYER_RANK_HIGH_SCHOOL',
  PLAYER_RANK_BACHELORS = 'PLAYER_RANK_BACHELORS',
  PLAYER_RANK_MASTERS = 'PLAYER_RANK_MASTERS',
  PLAYER_RANK_PHD = 'PLAYER_RANK_PHD',
  PLAYER_RANK_PROFESSOR = 'PLAYER_RANK_PROFESSOR',
  PLAYER_RANK_GRANDMASTER = 'PLAYER_RANK_GRANDMASTER',
  PLAYER_RANK_SUPER_GRANDMASTER = 'PLAYER_RANK_SUPER_GRANDMASTER',

}

export default AchievementType;
