export enum EmailType {
  EMAIL_CONFIRM_EMAIL = 'EMAIL_CONFIRM_EMAIL',
  EMAIL_DIGEST = 'EMAIL_DIGEST',
  EMAIL_MARKETING = 'EMAIL_MARKETING',
  EMAIL_7D_REACTIVATE = 'EMAIL_7D_REACTIVATE',
  EMAIL_10D_AUTO_UNSUBSCRIBE = 'EMAIL_10D_AUTO_UNSUBSCRIBE',
  EMAIL_PASSWORD_RESET = 'EMAIL_PASSWORD_RESET',
  EMAIL_WALL_POST = 'EMAIL_WALL_POST',
  EMAIL_WALL_REPLY = 'EMAIL_WALL_REPLY',
}

export enum EmailDigestSettingTypes {
  DAILY = 'DAILY',
  ONLY_NOTIFICATIONS = 'ONLY_NOTIFICATIONS',
  NONE = 'NONE',
}
