export enum EmailKVTypes {
  LAST_TS_EMAIL_DIGEST = 'EMAIL_DIGEST.LAST_TS.',
  LAST_TS_EMAIL_MARKETING = 'EMAIL_MARKETING.LAST_TS.',
  LAST_TS_EMAIL_7D_REACTIVATE = 'EMAIL_7D_REACTIVATE.LAST_TS.',
}
export enum EmailType {
  EMAIL_DIGEST = 'EMAIL_DIGEST',
  EMAIL_MARKETING = 'EMAIL_MARKETING',
  EMAIL_7D_REACTIVATE = 'EMAIL_7D_REACTIVATE',
  EMAIL_PASSWORD_RESET = 'EMAIL_PASSWORD_RESET',
}

export enum EmailDigestSettingTypes {
  DAILY = 'DAILY',
  ONLY_NOTIFICATIONS = 'ONLY_NOTIFICATIONS',
  NONE = 'NONE',
}
