enum NotificationType {
  ADMIN_MESSAGE = 'ADMIN_MESSAGE',
  LEVEL_OF_DAY = 'LEVEL_OF_DAY',
  NEW_ACHIEVEMENT = 'NEW_ACHIEVEMENT',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NEW_LEVEL = 'NEW_LEVEL',
  NEW_LEVEL_ADDED_TO_COLLECTION = 'NEW_LEVEL_ADDED_TO_COLLECTION',
  NEW_REVIEW_ON_YOUR_LEVEL = 'NEW_REVIEW_ON_YOUR_LEVEL',
  NEW_RECORD_ON_A_LEVEL_YOU_SOLVED = 'NEW_RECORD_ON_A_LEVEL_YOU_BEAT',
  NEW_WALL_POST = 'NEW_WALL_POST',
  NEW_WALL_REPLY = 'NEW_WALL_REPLY',
  UPGRADED_TO_PRO = 'UPGRADED_TO_PRO',
}

export default NotificationType;
