enum NotificationType {
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NEW_LEVEL_FROM_USER_YOU_FOLLOW = 'NEW_LEVEL_FROM_USER_YOU_FOLLOW',
  NEW_REVIEW_ON_YOUR_LEVEL = 'NEW_REVIEW_ON_YOUR_LEVEL',
  NEW_RECORD_ON_A_LEVEL_YOU_BEAT = 'NEW_RECORD_ON_A_LEVEL_YOU_BEAT',
}

export default NotificationType;
