enum NotificationType {
  NEW_ACHIEVEMENT = 'NEW_ACHIEVEMENT',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NEW_LEVEL = 'NEW_LEVEL',
  NEW_LEVEL_ADDED_TO_COLLECTION = 'NEW_LEVEL_ADDED_TO_COLLECTION',
  NEW_REVIEW_ON_YOUR_LEVEL = 'NEW_REVIEW_ON_YOUR_LEVEL',
  NEW_RECORD_ON_A_LEVEL_YOU_SOLVED = 'NEW_RECORD_ON_A_LEVEL_YOU_BEAT',
  NEW_WALL_POST = 'NEW_WALL_POST',
  NEW_WALL_REPLY = 'NEW_WALL_REPLY',
}

export default NotificationType;
