FROM node:18

ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /pathology_app

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

RUN npm install -g typescript ts-node 


#USER node

CMD ["npm","run", "dev"]