FROM  node:20

ENV NEXT_TELEMETRY_DISABLED=1

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update \
    && apt-get install -y chromium
WORKDIR /pathology_app

COPY --chown=node:node package*.json tsconfig-socket.json ./

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium

RUN npm install

# ts-node / tspath is needed for other scripts right now. module-alias is used for socket server production
# ideally all would use package module alias and we would not need ts-node / tspath. but that's a TODO
RUN npm install -g typescript ts-node tspath

COPY --chown=node:node . .

# only for the socket server container on PROD
# RUN tsc -p tsconfig-socket.json

# for dev you don't need to run tsc


# Uncomment the following line if you want to run the app as a non-root user
# USER node


CMD ["npm","run", "dev"]
