FROM node:18

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm install -g ts-node

WORKDIR /pathology_app

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

#USER node

CMD ["npm","run", "dev"]