enum AchievementCategory {
  SOCIAL = 'SOCIAL',
  PROGRESS = 'USER',
  CREATOR = 'CREATOR',
  SKILL = 'LEVEL_COMPLETION',
  REVIEWER = 'REVIEWER',
  MULTIPLAYER = 'MULTIPLAYER',
  CHAPTER_COMPLETION = 'CHAPTER_COMPLETION',
}

export default AchievementCategory;
