import { ObjectId } from 'bson';
import type { NextApiResponse } from 'next';
import Discord from '../../../constants/discord';
import NotificationType from '../../../constants/notificationType';
import { ValidNumber, ValidObjectId, ValidType } from '../../../helpers/apiWrapper';
import queueDiscordWebhook from '../../../helpers/discordWebhook';
import { TimerUtil } from '../../../helpers/getTs';
import { logger } from '../../../helpers/logger';
import { completedXAmountOfLevelsNotification } from '../../../helpers/notificationHelper';
import dbConnect from '../../../lib/dbConnect';
import withAuth, { NextApiRequestWithAuth } from '../../../lib/withAuth';
import { LevelModel, ReviewModel } from '../../../models/mongoose';
import { queueRefreshIndexCalcs } from '../internal-jobs/worker';