name: Deploy

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed
    branches: [main]

jobs:
  deploy-new-containers:
    name: Deploy New Containers
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/pathology
          chmod 600 ~/.ssh/pathology
          cat >>~/.ssh/config <<END
          Host pathology-server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/pathology
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}

      - name: Update Environments with New Containers
        run: ssh pathology-server 'bash /opt/pathology/scripts/update-Environments.sh'