import mongoose from 'mongoose';
import Achievement from './db/achievement';
import Cache from './db/cache';
import Campaign from './db/campaign';
import Collection from './db/collection';
import Comment from './db/comment';
import Device from './db/device';
import EmailLog from './db/emailLog';
import Graph from './db/graph';
import Image from './db/image';
import KeyValue from './db/keyValue';
import Level from './db/level';
import MultiplayerMatch from './db/multiplayerMatch';
import MultiplayerProfile from './db/multiplayerProfile';
import Notification from './db/notification';
import PlayAttempt from './db/playAttempt';
import QueueMessage from './db/queueMessage';
import Record from './db/record';
import { Report } from './db/report';
import Review from './db/review';
import Stat from './db/stat';
import { StripeEvent } from './db/stripeEvent';
import User from './db/user';
import UserAuth from './db/userAuth';
import UserConfig from './db/userConfig';
import AchievementSchema from './schemas/achievementSchema';
import CacheSchema from './schemas/cacheSchema';
import CampaignSchema from './schemas/campaignSchema';
import CollectionSchema from './schemas/collectionSchema';
import CommentSchema from './schemas/commentSchema';
import DeviceSchema from './schemas/deviceSchema';
import EmailLogSchema from './schemas/emailLogSchema';
import GraphSchema from './schemas/graphSchema';
import ImageSchema from './schemas/imageSchema';
import KeyValueSchema from './schemas/keyValueSchema';
import LevelSchema from './schemas/levelSchema';
import MultiplayerMatchSchema from './schemas/multiplayerMatchSchema';
import MultiplayerProfileSchema from './schemas/multiplayerProfileSchema';
import NotificationSchema from './schemas/notificationSchema';
import PlayAttemptSchema from './schemas/playAttemptSchema';
import QueueMessageSchema from './schemas/queueMessageSchema';
import RecordSchema from './schemas/recordSchema';
import ReportSchema from './schemas/reportSchema';
import ReviewSchema from './schemas/reviewSchema';
import StatSchema from './schemas/statSchema';
import StripeEventSchema from './schemas/stripeEventSchema';
import UserAuthSchema from './schemas/userAuthSchema';
import UserConfigSchema from './schemas/userConfigSchema';
import UserSchema from './schemas/userSchema';

// NB: need to initialize some models before they are referenced by other models
// (eg User before Collection since Collection has a User ref)
export const UserModel = mongoose.models.User || mongoose.model<User>('User', UserSchema);
export const UserAuthModel = mongoose.models.UserAuth || mongoose.model<UserAuth>('UserAuth', UserAuthSchema);
export const CollectionModel = mongoose.models.Collection || mongoose.model<Collection>('Collection', CollectionSchema);
export const CommentModel = mongoose.models.Comment || mongoose.model<Comment>('Comment', CommentSchema);
export const LevelModel = mongoose.models.Level || mongoose.model<Level>('Level', LevelSchema);
export const RecordModel = mongoose.models.Record || mongoose.model<Record>('Record', RecordSchema);
export const ReviewModel = mongoose.models.Review || mongoose.model<Review>('Review', ReviewSchema);
export const StatModel = mongoose.models.Stat || mongoose.model<Stat>('Stat', StatSchema);
export const ImageModel = mongoose.models.Image || mongoose.model<Image>('Image', ImageSchema);
export const UserConfigModel = mongoose.models.UserConfig || mongoose.model<UserConfig>('UserConfig', UserConfigSchema);
export const PlayAttemptModel = mongoose.models.PlayAttempt || mongoose.model<PlayAttempt>('PlayAttempt', PlayAttemptSchema);
export const MultiplayerMatchModel = mongoose.models.MultiplayerMatch || mongoose.model<MultiplayerMatch>('MultiplayerMatch', MultiplayerMatchSchema);
export const MultiplayerProfileModel = mongoose.models.MultiplayerProfile || mongoose.model<MultiplayerProfile>('MultiplayerProfile', MultiplayerProfileSchema);
export const NotificationModel = mongoose.models.Notification || mongoose.model<Notification>('Notification', NotificationSchema);
export const DeviceModel = mongoose.models.Device || mongoose.model<Device>('Device', DeviceSchema);
export const QueueMessageModel = mongoose.models.QueueMessage || mongoose.model<QueueMessage>('QueueMessage', QueueMessageSchema);
export const KeyValueModel = mongoose.models.KeyValue || mongoose.model<KeyValue>('KeyValue', KeyValueSchema);
export const GraphModel = mongoose.models.Graph || mongoose.model<Graph>('Graph', GraphSchema);
export const CampaignModel = mongoose.models.Campaign || mongoose.model<Campaign>('Campaign', CampaignSchema);
export const EmailLogModel = mongoose.models.EmailLog || mongoose.model<EmailLog>('EmailLog', EmailLogSchema);
export const AchievementModel = mongoose.models.Achievement || mongoose.model<Achievement>('Achievement', AchievementSchema);
export const StripeEventModel = mongoose.models.StripeEvent || mongoose.model<StripeEvent>('StripeEvent', StripeEventSchema);
export const ReportModel = mongoose.models.Report || mongoose.model<Report>('Report', ReportSchema);
export const CacheModel = mongoose.models.Cache || mongoose.model<Cache>('Cache', CacheSchema);
